### ISSUE TITLE
Feature: Make links shareable

### ISSUE THREAD

**Issue by Pdzly** [tgxn/lemmy-modder#118]
**What do you want to see?**
If you change something ( filters etc... ) that should be represented in the url for the user to save as a bookmark or share to other users.

**Comment by tgxn** [comment]
This is the same way [lemmy-explorer works](https://github.com/tgxn/lemmy-explorer/blob/main/frontend/src/components/Communities.jsx#L53C8-L55C24). Whenever you change the filters, it will update the query params.

I didn't know if I want to go in this direction yet with modder, were you thinking on the `reports` page only?

for `community` and `type` it seems kinda irrelevant, but if we add `actor_id` and maybe `reporter_id` then that might be more useful.

some examples that might be handy?
> `https://modder.lemmyverse.net/#/reports?actor_id=1234` - show all reports that relate to a user id
> `https://modder.lemmyverse.net/#/reports?community=1234` - show all reports in community

🤷‍♂️ it feels like something that might not get much use but happy if someone wants to contribute

**Comment by Pdzly** [comment]
It will get much use on the mod logs page, as an moderator, you want to watch out for some "suspicious" users, moderators can just put in the filters for that user on the modlogs, and he can just make multiple. Another way we can do that is like in website bookmarks. 

I will look for a oportunity to contribute this to modlogs, ( secondary to the reports )

Modlogs would be super easy, the reports in the other hand would be tricky, as they dont have a official api on lemmy.
