### ISSUE TITLE
Creative commons licenses are not recommended for software

### ISSUE THREAD

**Issue by wiki-me** [tgxn/lemmy-modder#16]
See [here](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software).

Since this seems like something that could run on a server, i think licensing this as AGPL is better.

**Comment by tgxn** [comment]
What if I apply https://mit-license.org/ to it? That's typically how I license my stuff.

**Comment by tgxn** [comment]
merged MIT, closing 😘
