### ISSUE TITLE
User/Instance Growth Statistics

### ISSUE THREAD

**Issue by tgxn** [tgxn/lemmy-modder#59]
I have this data available from the Lemmy Explorer dumps, which can show instance growth numbers for each instance.

This ticket would integrate this data into Lemmy Modder, to allow mods to:
- View User Growth
- View Post/Comment Growth

More difficult, and maybe related to #50 - we could pull additional statistics directly from the Lemmy DB, for example:
- Number of reports dealt with in the past ~week
- Number of reports resolved without content removal
- Most active mods (maybe also data from modlog)

From https://beehaw.org/post/574562

**Comment by Pdzly** [comment]
I have some thoughts about the risk and possible performance issue if you would directly hook into the database of an lemmy instance. Could be a security risk if wrongly implemented. Or just a performance bottleneck. 

I would see a possibility in #60  to make this possible. For example that it could use its own source, like a pre cached database, static file that gets updated or just direct access. They can choose directly who has access to that data.

And the responsibility goes further away from you of dealing with spam, authorisation and so on.

**Comment by tgxn** [comment]
This feature would be sources solely from the lemmyverse data exports.

This would be a new "home" page that all users have access to. This would just report on the latest instance metrics and stats/versions, etc.
