### ISSUE TITLE
NSFW Content Report Options

### ISSUE THREAD

**Issue by tgxn** [tgxn/lemmy-modder#63]
https://lemmy.tgxn.net/comment/305035
> My approach would be to add certain keywords to the report message (“porn”, “CSAM”, “child” in various languages, or make it a textbox where mods can enter words themselves) and hide the image by default when the message contains any of those, with a click-to-expand feature to actually verify reports.
> I don’t think relying on the NSFW flag is very useful against abuse, though it could be a good feature for moderators of instances that have NSFW communities.

I think this is valid, as sometimes we don't want to see the NSFW content, or have it downloaded, when we are just viewing a list of reports.
There are a couple things that could help with this:
- Setting "Display content preview for NSFW posts"
Default this option to your user-setting "blur_nsfw" or "hide_nsfw".

Stretch Goal:
- Setting "Hide content preview with reports containing <words>"
This would allow hiding content on reports that contain a matching word in the body of the users report submission.

**Comment by Pdzly** [comment]
I would add a "Spotlight" to each image you show. 

Spotlight: 
Not hovering - Picture is black
Hovering - Small area of picture is revealed
Clicking - Toggling it on / off

This technique is used by few other Social Medias for reducing stress seeing CP or general porn.

**Comment by Pdzly** [comment]
https://rooki-bot.lemmy.world/ The spotlight i imagine i implemented here.

![image](https://github.com/tgxn/lemmy-modder/assets/34943569/a15e0f74-ed2d-4120-95f7-68c579b87e36)


Some other interesting features:

![image](https://github.com/tgxn/lemmy-modder/assets/34943569/ff8fca04-8a88-4628-b678-a4db5997220a)

**Comment by tgxn** [comment]
> https://rooki-bot.lemmy.world/ The spotlight i imagine i implemented here.

where's the src? can I use this on my site?
