### ISSUE TITLE
No "Go Back" Button

### ISSUE THREAD

**Issue by Pdzly** [tgxn/lemmy-modder#77]
After you go to the mod logs, you cant go back without editing the url. 

As far i can see there is no current "Go Back" button.
![image](https://github.com/tgxn/lemmy-modder/assets/34943569/8cf45d92-bd37-4ec2-a249-739d5386d82f)

**Comment by Pdzly** [comment]
Ok after looking into it. There should be a button with "Reports" But somehow it isnt visible.

**Comment by tgxn** [comment]
Very true... Though, for non-community mods, the only page available would be the modlog...

Probably worth making it more obvious that that's all you get - I am gonna add some kind of instance overview page (for #59) as the homepage soon, so users will also get access to that.
